baseURL = "/"
languageCode = "en-us"
title = "EU19 Tracking Exposed"
theme = "eutrex"
enableRobotsTXT = true
canonifyURLs = true
[params]
  description = "EU election 2019 Tracking expose. A collaborative observatory of algorithm influences, and few citizen driven solutions."
  style = ""

[permalinks]
  posts = "/:slug/"

#sectionPagesMenu = "main"



menu = ["main", "footer"]

 [[menu.main]]
    page = "Pages"
    identifier = "pages"
    name = "Pages"
    url = "#"
    weight = -100
 [[menu.main]]
    page = "Researcher"
    identifier = "researcher"
    name = "Researcher"
    url = "/page/researcher/"
    parent = "pages"
    weight = -110
 [[menu.main]]
    page = "Individual"
    identifier = "Individual"
    parent = "pages"
    name = "Individual"
    url = "/page/individual/"
    weight = -120
 [[menu.main]]
    page = "Candidate"
    identifier = "candidate"
    parent = "pages"
    name = "Candidates"
    url = "/page/candidate/"
    weight = -130
 [[menu.main]]
    page = "Ethos"
    identifier = "ethos"
    name = "Goals and ethos"
    parent = "pages"
    url = "/page/ethos/"
    weight = -140
 [[menu.main]]
    page = "RSS"
    identifier = "rss"
    parent = "pages"
    name = "Watch events"
    url = "/page/rss/"
    weight = -150
 [[menu.main]]
    page = "Country"
    identifier = "country"
    name = "Countries"
    url = "/country/"
    weight = -160
 [[menu.main]]
    page = "Language"
    identifier = "language"
    name = "Languages"
    url = "/language/"
    weight = -170
 [[menu.main]]
    page = "trackers"
    identifier = "trackers"
    name = "Trackers"
    url = "/page/trackers/"
    weight = -180


 [[menu.footer]]
    page = "get-the-extension"
    identifier = "get-the-extension"
    name = "Get the extension"
    url = "/page/get-the-extension/"
    weight = -110
 [[menu.footer]]
     page = "Researcher"
     identifier = "researcher"
     name = "Researcher"
     url = "/page/researcher/"
     weight = -120
 [[menu.footer]]
     page = "Individual"
     identifier = "individual"
     name = "Individual"
     url = "/page/individual/"
     weight = -130
 [[menu.footer]]
     page = "Candidate"
     identifier = "candidate"
     name = "Candidates"
     url = "/page/candidate/"
     weight = -140
 [[menu.footer]]
     page = "Ethos"
     identifier = "ethos"
     name = "Goals and ethos"
     url = "/page/ethos/"
     weight = -150
 [[menu.footer]]
     page = "RSS"
     identifier = "rss"
     name = "Watch events horizontally"
     url = "/page/rss/"
     weight = -160
 [[menu.footer]]
     page = "trackers"
     identifier = "trackers"
     name = "Trackers"
     url = "/page/trackers/"
     weight = -170